# Generated by Django 5.2 on 2025-04-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='institute',
        ),
    ]
